config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/AboutTheBible',:as => 'aboutthebible_page'

  get 'staticpages/FAQ',:as => 'FAQ_page'

  get 'staticpages/Links',:as => 'Links_page'

  get 'staticpages/BibleTranslation',:as => 'bibletranslation_page'

  get 'staticpages/QuickRef',:as => 'quickref_page'

  get 'staticpages/Sample',:as => 'sample_page'

  get 'staticpages/Subject',:as => 'subject_page'

  get 'staticpages/Gospel',:as => 'gospel_page'

  get 'staticpages/Books',:as => 'books_page'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

   root 'home#index'

  resources :tables, except: [:show, :index]
  get 'table/new' => redirect('tables/new')
  get 'table' => 'tables#show', as: :show_table
  get 'tables' => redirect('table')
  post 'table/exit' => 'tables#exit_table', as: :exit_table

  resources :orders, only: [:new, :create]
  post 'orders/create_table_order' => 'orders#create_table_order', as: :create_table_order

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create]

  namespace :admin do
    get '/' => 'home#index', as: :root
    get '/orders' => 'search#index'
    get '/duplicates_csv' => 'search#duplicates_csv'

    resources :users, only: [:index, :edit, :update]

    resources :customers, only: [:new, :create, :edit, :update] do
      post 'find_duplicate_by_name_or_address', on: :collection
      member do
        get 'find_duplicate'
        post 'merge'
      end
      resources :orders, only: [:new, :create, :destroy, :update]
    end

    resources :labels, only: [:index]
    resources :shipments, only: [:index, :show]
    resources :contact_lists, only: [:index, :show, :create]
    resources :coordinators, except: [:show, :destroy]
    resources :users
    resources :inventories do
      collection do
        post :stock_take
        post :stock_in
        post :reset_table
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'available_items' => 'home#available_items'
      post 'validate_order' => 'orders#validate'
      post 'orders' => 'orders#create'
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :territorial_authority, optional: true
  belongs_to :created_by, class_name: 'User', optional: true
  belongs_to :updated_by, class_name: 'User', optional: true
  has_many :merged_customers, class_name: 'Customer', foreign_key: 'parent_id'

  enum :further_contact_requested, [:not_specified, :not_wanted, :wanted], prefix: :further_contact_requested
  normalize_attributes :first_name, :last_name, :email, :address
  normalize_attribute :phone, with: :phone

  scope :customer_id, ->(customer_id) { where("customers.id = ?", customer_id) }
  scope :first_name, ->(first_name) { where("lower(customers.first_name) LIKE ?", "%#{first_name.downcase}%") }
  scope :last_name, ->(last_name) { where("lower(customers.last_name) LIKE ?", "%#{last_name.downcase}%") }
  scope :email, ->(email) { where("lower(customers.email) LIKE ?", "%#{email.downcase}%") }
  scope :phone, ->(phone) { where("customers.phone LIKE ?", "%#{strip_non_numeric(phone)}%") }
  scope :address, ->(address) { where("lower(customers.address) LIKE ?", "%#{address.downcase}%") }
  scope :suburb, ->(suburb) { where("lower(customers.suburb) LIKE ?", "%#{suburb.downcase}%") }
  scope :city_town, ->(city_town) { where("lower(customers.city_town) LIKE ?", "%#{city_town.downcase}%") }
  scope :further_contact_requested, ->(further_contact_requested) {
    where(further_contact_requested: further_contact_requested)
  }
  scope :contactable, -> {
    where(further_contact_requested: self.further_contact_requesteds[:wanted]).
      where(contact_list_id: nil)
  }
  scope :for_districts, ->(ids) {
    where(territorial_authority_id: ids)
  }
  scope :district, ->(id) {
    where(territorial_authority_id: id)
  }
  scope :can_ship_to, -> {
      where(bad_address: false).where.not("further_contact_requested = #{Customer.further_contact_requesteds[:not_wanted]}")
  }

  attr_accessor :confirm_personal_order, :item_ids

  def self.strip_non_numeric(string)
    string.gsub(/\D/, '')
  end

  # when ta name is set, also set the TA association
  def ta=(name)
    super
    self.territorial_authority = TerritorialAuthority.find_by_name(name)
  end

  def identifier
    "##{id}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_email?
    email.present?
  end
end

app/controllers/admin/customers_controller.rb
module Admin
  class CustomersController < BaseController
    before_action :permit_params

    def new
      @new_customer_form = NewCustomerForm.new(params[:admin_new_customer_form])
    end

    def create
      @new_customer_form = NewCustomerForm.new(params[:admin_new_customer_form])

      create_customer = CreateCustomerService.new(user: current_user,
                                                  form: @new_customer_form).perform
      if create_customer.success?
        redirect_to new_admin_customer_path, notice: "Customer created successfully. Customer Id: #{view_context.link_to(create_customer.cust_id, edit_admin_customer_path(create_customer.cust_id))}"
      else
        @duplicates_by_name    = duplicates_by_name(@new_customer_form.first_name, @new_customer_form.last_name)
        @duplicates_by_address = duplicates_by_address(@new_customer_form.pxid)
        render :new
      end
    end

    def edit
      @edit_view_model = Customers::EditView.new(customer)
      @customer_form = ExistingCustomerForm.new(customer: customer, form_params: params[:admin_existing_customer_form])
    end

    def update
      @customer_form = ExistingCustomerForm.new(customer: customer, form_params: params[:admin_existing_customer_form])
      @update_customer = UpdateCustomerService.new(current_user, @customer_form).perform
    end

    def find_duplicate
      @merge_form = MergeCustomerForm.new(original: customer, duplicate_id: params[:customer_id])
      @merge_view = Customers::MergeView.new(original: @merge_form.original, duplicate: @merge_form.duplicate)
    end

    def find_duplicate_by_name_or_address
      @duplicates_by_name    = duplicates_by_name(params[:first_name], params[:last_name])
      @duplicates_by_address = duplicates_by_address(params[:pxid])
    end

    def merge
      merge_form = MergeCustomerForm.new(original: customer, duplicate_id: params[:duplicate_id])
      @merge_customer = MergeCustomerService.new(user: current_user, form: merge_form).perform
      @edit_view_model = Customers::EditView.new(customer.reload)
    end

    private

    def customer
      @customer ||= Customer.find(params[:id])
    end

    def duplicates_by_name first_name, last_name
      return nil if first_name.blank?
      return nil if last_name.blank?

      Customer.where(first_name: first_name, last_name: last_name)
    end

    def duplicates_by_address pxid
      return nil if pxid.blank?

      Customer.where(pxid: pxid)
    end

  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
  def contact_requested_options_for_select
    Customer.further_contact_requesteds.map { |k,v| [k.humanize, v] }
  end

  def selected_further_contact_requested(customer_form)
    return contact_requested_options_for_select.assoc(customer_form.further_contact_requested.capitalize.tr("_", " ")).last if customer_form.present?
    contact_requested_options_for_select
  end
end

app/views/admin/customers/_customer.html.erb
<h4>Customer <%= view_model.customer_identifier %></h4>

<dl>
  <dd><%= view_model.name %></dd>
  <dd><%= view_model.address %></dd>
</dl>
<dl>
  <dt>Phone number</dt>
  <dd><%= view_model.phone %></dd>
</dl>
<dl>
  <dt>Email</dt>
  <dd><%= view_model.email %></dd>
</dl>

app/views/admin/customers/_editable_order.html.erb
<h4>Order <%= view_model.order_identifier %></h4>
<% form = view_model.form %>
<%= form_for [:admin, form], url: admin_customer_order_path(view_model.customer_id, view_model.order_id), method: :put, html: {id: view_model.form_id, remote: true, role: 'form'} do |f| %>
  <div class="col-md-4">
    <dl>
      <dt>Date ordered:</dt>
      <dd><%= view_model.date_ordered %></dd>
    </dl>
    <dl>
      <dt>Method received:</dt>
      <dd><%= f.select :method_received, methods_received_for_select(form), {}, class: "form-control" %></dd>
    </dl>
    <dl>
      <dt>How heard:</dt>
      <dd><%= f.select :method_of_discovery, discovery_methods_for_select(form), {}, class: "form-control" %></dd>
    </dl>
  </div>
  <div class="col-md-8">
    <dl>
      <dt>Titles requested:</dt>
      <dd class="error_msg"><%= form.errors[:item_ids].join %></dd>
      <dd><%= f.select :item_ids, items_for_select(view_model), {}, multiple: 'multiple', size: 6, class: "form-control" %></dd>
    </dl>
  </div>
  <div class="col-md-12">
    <%= f.submit "Update order", class: 'btn btn-success' %>
    <%= link_to "Cancel order", admin_customer_order_path(view_model.customer_id, view_model.order_id), method: :delete, remote: true, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/admin/customers/_form.html.erb
<%= form_for [:admin, customer_form], url: admin_customer_path(customer_form.customer), method: :patch, remote: true, html: {role: "form", class: "form-horizontal"} do |f| %>
  <div class="col-sm-8">
    <div class="form-group">
      <div class="col-sm-4">
        <%= f.required_label :title, class: "control-label"%>
        <%= f.select :title, titles_for_select(customer_form), {include_blank: 'Unknown'}, class: "form-control"%>
      </div>
      <div class="col-sm-4">
        <%= f.required_label :first_name, class: "control-label" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.required_label :last_name, class: "control-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-8">
        <%= f.label :address, "Postal Address", class: "control-label" %>
        <%= f.text_area :address, class: "addressfinder_widget form-control", placeholder: "Start typing to see a list of addresses to choose from", rows: 1 %>
        <%= f.hidden_field :suburb, class: "hidden-address suburb" %>
        <%= f.hidden_field :city_town, class: "hidden-address city_town" %>
        <%= f.hidden_field :post_code, class: "hidden-address post_code" %>
        <%= f.hidden_field :pxid, class: "hidden-address pxid" %>
        <%= f.hidden_field :dpid, class: "hidden-address dpid" %>
        <%= f.hidden_field :x, class: "hidden-address x" %>
        <%= f.hidden_field :y, class: "hidden-address y" %>
      </div>
      <div class="col-sm-4">
        <%= f.required_label :ta, label_text: "District", class: "control-label" %>
        <%= f.select :ta, territorial_authorities_for_select(customer_form), {include_blank: true}, class: "form-control hidden-address ta" %>
      </div>
      <div class=" checkbox col-sm-6">
        <%= f.label :bad_address do %>
          <%= f.check_box :bad_address %>Bad address?
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6">
        <%= f.label :phone, class: "control-label" %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="col-sm-6">
        <%= f.label :email, class: "control-label" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="checkbox col-sm-6">
        <%= f.label :tertiary_student do %>
          <%= f.check_box :tertiary_student, class: 'tertiary-institution-toggle' %>Is the order for a tertiary student?
        <% end %>
      </div>
      <div id="tertiary_institution" class="col-sm-6">
        <%= f.label :tertiary_institution, class: "control-label" %>
        <%= f.text_field :tertiary_institution, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6">
        <%= render 'further_contact_requested', form: f %>
      </div>
      <div class="col-sm-6">
        <dl>
          <dt><%= f.label 'Date customer record created' %></dt>
          <dd><%= customer_form.date_created %></dd>
        </dl>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :admin_notes, "Notes", class: "control-label" %>
      <%= f.text_area :admin_notes, class: 'form-control', rows: 10 %>
    </div>
  </div>
  <div class="btn-toolbar">
    <div class="col-sm-8">
      <%= f.submit "Update Customer", class: "btn btn-primary" %>
      <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/customers/_further_contact_requested.html.erb
<%= form.label :further_contact_requested, "Are they interested in receiving further contact?" %>
<%= form.select :further_contact_requested, options_for_select(contact_requested_options_for_select, selected_further_contact_requested(@customer_form)), {}, { class: "form-control" } %>

app/views/admin/customers/_merge_preview.html.erb
<%= render 'customer', view_model: view_model.show_view_model %>
<% if view_model.order_view_models.any? %>
  <% view_model.order_view_models.each do |order_view| %>
    <%= render 'order', view_model: order_view %>
  <% end %>
<% else %>
  This customer has no orders
<% end %>
<div class="col-md-12">
  <hr>
  <b>Note:</b> this is an irreversible operation. Customer <%= view_model.duplicate_identifier %> will be merged into Customer <%= view_model.original_identifier %>. Customer <%= view_model.original_identifier %> address and contact details will remain, Customer <%= view_model.duplicate_identifier %>'s details will be removed. All of Customer <%= view_model.duplicate_identifier %>'s orders will be added to Customer <%= view_model.original_identifier %>.
  <%= link_to "Merge Customer #{view_model.duplicate_identifier} into Customer #{view_model.original_identifier}", merge_admin_customer_path(id: view_model.original_id, duplicate_id: view_model.duplicate_id), class: 'btn btn-default', method: :post, remote: true %>
  <%= link_to 'Cancel', edit_admin_customer_path(view_model.original_id), class: 'btn btn-default', id: 'cancel-merge' %>
</div>

app/views/admin/customers/_merged_customer.html.erb
<h4>Customer <%= view_model.customer_identifier %></h4>

<div class="col-md-4">
  <dl>
    <dd><%= view_model.name %></dd>
    <dd><%= view_model.address %></dd>
  </dl>
  <dl>
    <dt>Phone number</dt>
    <dd><%= view_model.phone %></dd>
  </dl>
  <dl>
    <dt>Email</dt>
    <dd><%= view_model.email %></dd>
  </dl>
</div>

<div class="col-md-4">
  <dl>
    <dt>Method received</dt>
    <dd><%= view_model.method_received %></dd>
  </dl>
  <dl>
    <dt>How heard</dt>
    <dd><%= view_model.method_of_discovery %></dd>
  </dl>
</div>

app/views/admin/customers/_merged_customers.html.erb
<div class="col-md-6">
    <%= form_tag(find_duplicate_admin_customer_path(view_model.customer_id), method: :get, id: "find-customer-form", remote: true) do %>
      <%= label_tag :customer_id, 'Customer #' %>
      <%= text_field_tag :customer_id %>
      <%= submit_tag "Look up customer", class: 'btn btn-default' %>
    <% end %>
    <% view_model.merged_customer_views.each do |merged_customer_view| %>
      <div class="row">
        <%= render 'customer', view_model: merged_customer_view %>
      </div>
    <% end %>
    <%= link_to "Merge another customer into this one", '#', class: 'btn btn-default', id: 'find-customer-to-merge' %>
  </div>
  <div id="merge-preview" class="col-md-6"></div>

app/views/admin/customers/_order.html.erb
<h4>Order <%= view_model.order_identifier %></h4>
<div class="col-md-4">
  <dl>
    <dt>Date ordered:</dt>
    <dd><%= view_model.date_ordered %></dd>
  </dl>
  <dl>
    <dt>Date shipped:</dt>
    <dd><%= view_model.date_shipped %></dd>
  </dl>
</div>

<div class="col-md-8">
  <dl>
    <dt>Titles ordered:</dt>
    <dd><%= view_model.titles_ordered.join("<br>").html_safe %></dd>
  </dl>
</div>

app/views/admin/customers/_orders.html.erb
<% view_model.order_views.each do |order_view| %>
  <div class="row">
    <%= render order_view.partial, view_model: order_view %>
  </div>
<% end %>
<br>
<div class="row">
  <%= link_to "Add new order", new_admin_customer_order_path(view_model.customer), class: 'btn btn-default', remote: true %>
  <div class="row" id="order-form"></div>
</div>

app/views/admin/customers/edit.html.erb
<h2 class="customer">Customer <%= @edit_view_model.customer_identifier %><span class="flash"></span></h2>
<div id="customer-form" class="row">
  <%= render 'form', customer_form: @customer_form %>
</div>

<div class="row">
  <h2 class="orders">Orders<span class="flash"></span></h2>
  <% if @edit_view_model.cannot_ship_orders? %>
    <div class="col-md-12">
      <dl>
        <dd class="error_msg">Orders not shippable: <%= @edit_view_model.not_shippable_reason %></dd>
      </dl>
    </div>
  <% end %>

  <div class="col-sm-10" id="orders">
    <%= render 'orders', view_model: @edit_view_model %>
  </div>
</div>

<div class="row merged-customers">
  <h2 class="merged-customer-records">Merged Customer Records<span class="flash"></span></h2>
  <div class="col-sm-12" id="merged-customers">
    <%= render 'merged_customers', view_model: @edit_view_model %>
  </div>
</div>

app/views/admin/customers/find_duplicate.js.erb
<% if @merge_form.valid? %>
  $("#merge-preview").html("<%= escape_javascript(render 'admin/customers/merge_preview', view_model: @merge_view) %>")
<% else %>
  $("#merge-preview").html("")
  <% flash_type = :error %>
<% end %>

<%= render 'shared/flash_messages', header_class: 'merged-customer-records', text: @merge_form.error_message, type: flash_type %>

app/views/admin/customers/find_duplicate_by_name_or_address.js.erb
$(".duplicates-by-name-or-address").html("<%= escape_javascript(
  render 'duplicates_by_name_or_address',
  duplicates_by_name:    @duplicates_by_name,
  duplicates_by_address: @duplicates_by_address
)%>")

app/views/admin/customers/new.html.erb
<h2>Add a new customer</h2>
<%= form_for [:admin, @new_customer_form], url: admin_customers_path, html: {role: "form", class: "form-horizontal"} do |f| %>
  <div class="col-sm-6">
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.required_label :title, class: "control-label"%>
        <%= f.select :title, titles_for_select(@new_customer_form), {include_blank: 'Unknown'}, class: "form-control", :autofocus => true %>
      </div>
      <div class="col-sm-4">
        <%= f.required_label :first_name, class: "control-label" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.required_label :last_name, class: "control-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6">
        <%= f.label :address, "Postal Address", class: "control-label" %>
        <%= f.text_area :address, class: "addressfinder_widget form-control", placeholder: "Start typing to see a list of addresses to choose from", rows: 1 %>
        <%= f.hidden_field :suburb, class: "hidden-address suburb" %>
        <%= f.hidden_field :city_town, class: "hidden-address city_town" %>
        <%= f.hidden_field :post_code, class: "hidden-address post_code" %>
        <%= f.hidden_field :pxid, class: "hidden-address pxid" %>
        <%= f.hidden_field :dpid, class: "hidden-address dpid" %>
        <%= f.hidden_field :x, class: "hidden-address x" %>
        <%= f.hidden_field :y, class: "hidden-address y" %>
      </div>
      <div class="col-sm-3">
        <%= f.required_label :ta, label_text: "District", class: "control-label" %>
        <%= f.select :ta, territorial_authorities_for_select(@new_customer_form), {include_blank: true}, class: "form-control hidden-address ta" %>
      </div>
      <div class=" checkbox col-sm-6">
        <%= f.label :bad_address do %>
          <%= f.check_box :bad_address %>Bad address?
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-4">
        <%= f.label :phone, class: "control-label" %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.label :email, class: "control-label" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-4">
        <%= f.label :method_received, class: "control-label"%>
        <%= f.select :method_received, methods_received_for_select(@new_customer_form), {include_blank: true}, class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.label :method_of_discovery, class: "control-label"%>
        <%= f.select :method_of_discovery, discovery_methods_for_select(@new_customer_form), {include_blank: true}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="checkbox col-sm-6">
        <%= f.label :tertiary_student do %>
          <%= f.check_box :tertiary_student, class: 'tertiary-institution-toggle' %>Is the order for a tertiary student?
        <% end %>
      </div>
      <div id="tertiary_institution" class="col-sm-6">
        <%= f.label :tertiary_institution, class: "control-label" %>
        <%= f.text_field :tertiary_institution, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="form-group">
      <%= f.label :admin_notes, "Notes", class: "control-label" %>
      <%= f.text_area :admin_notes, class: 'form-control', rows: 10 %>
    </div>
  </div>

  <div class="col-sm-3" tabindex="100">
    <div class="duplicates-by-name-or-address">
      <%= render 'duplicates_by_name_or_address',
        duplicates_by_name:    @duplicates_by_name,
        duplicates_by_address: @duplicates_by_address
      %>
    </div>
  </div>

  <div class="col-sm-8">
    <div class="form-group">
      <div class="col-sm-6">
        <%= render 'further_contact_requested', form: f %>
      </div>
    </div>
    <div class="form-group">
      <h4>Titles requested</h4>
      <div class="error_msg"><%= @new_customer_form.errors[:item_ids].join %></div>
      <%= f.select :item_ids, items_for_select(@new_customer_form), {}, id: 'item_list', class: 'imagepicker', multiple: 'multiple' %>
    </div>

    <div class="form-group">
      <div class="checkbox col-sm-6">
        <%= f.label :received_in_person do %>
          <%= f.check_box :received_in_person %>This order has already been delivered.
        <% end %>
      </div>
    </div>
  </div>

  <div class="btn-toolbar">
    <div class="col-sm-8">
      <%= f.submit "Save and add another", class: "btn btn-primary" %>
      <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/customers/update.js.erb
<% if @update_customer.success? %>
  <% flash_type = :success %>
<% else %>
  <% flash_type = :error %>
  $("#customer-form").html("<%= escape_javascript(render 'form', customer_form: @customer_form) %>")
<% end %>

<%= render 'shared/flash_messages', header_class: 'customer', text: @update_customer.message, type: flash_type %>