config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/AboutTheBible',:as => 'aboutthebible_page'

  get 'staticpages/FAQ',:as => 'FAQ_page'

  get 'staticpages/Links',:as => 'Links_page'

  get 'staticpages/BibleTranslation',:as => 'bibletranslation_page'

  get 'staticpages/QuickRef',:as => 'quickref_page'

  get 'staticpages/Sample',:as => 'sample_page'

  get 'staticpages/Subject',:as => 'subject_page'

  get 'staticpages/Gospel',:as => 'gospel_page'

  get 'staticpages/Books',:as => 'books_page'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

   root 'home#index'

  resources :tables, except: [:show, :index]
  get 'table/new' => redirect('tables/new')
  get 'table' => 'tables#show', as: :show_table
  get 'tables' => redirect('table')
  post 'table/exit' => 'tables#exit_table', as: :exit_table

  resources :orders, only: [:new, :create]
  post 'orders/create_table_order' => 'orders#create_table_order', as: :create_table_order

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create]

  namespace :admin do
    get '/' => 'home#index', as: :root
    get '/orders' => 'search#index'
    get '/duplicates_csv' => 'search#duplicates_csv'

    resources :users, only: [:index, :edit, :update]

    resources :customers, only: [:new, :create, :edit, :update] do
      post 'find_duplicate_by_name_or_address', on: :collection
      member do
        get 'find_duplicate'
        post 'merge'
      end
      resources :orders, only: [:new, :create, :destroy, :update]
    end

    resources :labels, only: [:index]
    resources :shipments, only: [:index, :show]
    resources :contact_lists, only: [:index, :show, :create]
    resources :coordinators, except: [:show, :destroy]
    resources :users
    resources :inventories do
      collection do
        post :stock_take
        post :stock_in
        post :reset_table
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'available_items' => 'home#available_items'
      post 'validate_order' => 'orders#validate'
      post 'orders' => 'orders#create'
    end
  end
end

app/models/form/order.rb
class Form::Order
  include Virtus.model
  include ActiveModel::Model

  attribute :title, String
  attribute :first_name, String
  attribute :last_name, String

  attribute :address, String
  attribute :suburb, String
  attribute :city_town, String
  attribute :post_code, String
  attribute :pxid, String
  attribute :ta, String

  attribute :phone, String
  attribute :email, String

  attribute :tertiary_student, Virtus::Attribute::Boolean
  attribute :tertiary_institution, String

  attribute :item_ids, Array[Integer]

  attribute :further_contact_requested, Virtus::Attribute::Boolean

  validates :title, :first_name, :last_name, :address, presence: true
  validate :contains_at_least_one_item

  def order_attr_keys
    %w{item_ids}
  end

  def customer_attr_keys
    %w{title first_name last_name address suburb city_town post_code pxid ta phone email tertiary_student tertiary_institution further_contact_requested}
  end

  def order_attributes
    attributes.stringify_keys.slice(*order_attr_keys)
  end

  def customer_attributes
    attributes.stringify_keys.slice(*customer_attr_keys)
  end

  def item_ids=(item_ids)
    super item_ids.reject(&:blank?)
  end

  private

  def contains_at_least_one_item
    errors.add(:item_ids, "You must select at least one item") if item_ids.none?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :items
  belongs_to :table, optional: true
  belongs_to :shipment, optional: true
  belongs_to :customer, optional: true
  belongs_to :created_by, class_name: 'User', optional: true
  belongs_to :updated_by, class_name: 'User', optional: true

  paginates_per 20

  enum :method_of_discovery, [:unknown, :mail_disc, :uni_lit, :non_uni_lit, :other_ad, :word_of_mouth, :website, :other_disc, :table_disc], prefix: :method_of_discovery
  enum :method_received, [:mail, :phone, :personally_delivered, :internet, :other, :table], prefix: :method_received

  scope :created_between, ->(from, to) { where("orders.created_at >= ? AND orders.created_at < ?", from.in_time_zone, to.in_time_zone + 1.day) }
  scope :shipped_between, ->(from, to) { joins(:shipment).where("shipments.created_at >= ? AND shipments.created_at < ?", from.in_time_zone, to.in_time_zone + 1.day) }
  scope :id, ->(id) { where(id: id) }
  scope :shipped, -> { where("orders.shipment_id IS NOT NULL") }
  scope :ready_to_ship, -> {
    where(shipment_id: nil ).joins(:customer).merge(Customer.can_ship_to)
  }
  scope :item_ids, ->(item_ids) { joins(:items).where(items: {id: item_ids}) }

  attr_writer :received_in_person

  def received_in_person?
    @received_in_person
  end

  def shipped?
    shipment_id.present?
  end

  def shipped_at
    shipment.created_at
  end

  def identifier
    "##{customer_id}.#{id}"
  end

  def item_codes
    items.map(&:code).sort.join
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < BaseController
    before_action :permit_params

    def new
      @order_form = NewOrderForm.new(customer: customer)
    end

    def create
      @order_form = NewOrderForm.new(customer: customer,
                                     form_params: params[:admin_new_order_form])
      @create_order = ::Admin::CreateOrderService.new(user: current_user,
                                             form: @order_form).perform
      @edit_customer_view = Customers::EditView.new(customer)
    end

    def update
      order_form = ExistingOrderForm.new(order: order, form_params: params[:admin_existing_order_form])
      @update_order = UpdateOrderService.new(current_user: current_user,
                                             order: order,
                                             form: order_form).perform
      @order_view_model = Orders::EditView.new(order, order_form)
    end

    def destroy
      @cancel_order = CancelOrderService.new(order: order,
                                             user: current_user).perform
      @edit_customer_view = Customers::EditView.new(customer)
    end

    private

    def order
      @order ||= customer.orders.find(params[:id])
    end

    def customer
      @customer ||= Customer.find(params[:customer_id])
    end
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::BaseController
  before_action :authenticate!

  def validate
    order = CustomerAndOrderForm.new(order_params)
    response = order.valid? ? { success: true } : { success: false, errors: order.errors.full_messages }
    render(json: response, status: (order.valid? ? 200 : 400))
  end

  def create
    order = CustomerAndOrderForm.new(order_params)
    order_service = CreateOrderService.new(request, order)
    if !order.errors.present? && order_service.save
      render('/api/v1/order', locals: { order: order_service.order.reload })
    else
      render(json: { success: false, errors: order.errors.full_messages }, status: 400)
    end
  end

  private

  def order_params
    params.require(:order).permit(:title, :first_name, :last_name, :address, :suburb, :city_town, :post_code, :phone,
                                  :email, :further_contact_requested, item_ids: [])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :permit_params, :setup_order_form

  def new
  end

  def create
    order_service = CreateOrderService.new(request, @order_form)
    if order_service.save
      redirect_to root_path, notice: "Thanks, your order will be shipped as soon as possible"
    else
      render :new
    end
  end

  def create_table_order
    order_service = CreateOrderService.new(request, @order_form, table_id)
    if order_service.save
      redirect_to show_table_path, notice: "Form submitted successfully. Have a great day!" # better wording for the notice?
    else
      flash[:error] = @order_form.errors.full_messages.join("<br>")
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def setup_order_form
    preloaded_settings = params[:action] == "create_table_order" ? {confirm_personal_order: '1', item_ids: [Item.find_by(code: "R").id]} : {}
    @order_form ||= params[:customer_and_order_form] ?
      CustomerAndOrderForm.new(params[:customer_and_order_form].merge(preloaded_settings)) :
      CustomerAndOrderForm.new({})
  end

  def table_id
    params[:table_id]
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def territorial_authorities_for_select(form)
    options_for_select(TerritorialAuthority.all.map { |ta| [ta.name, ta.name] }, form.ta)
  end

  def method_of_discovery_options
    Order.method_of_discoveries.map do |k,v|
      case k.to_s
      when 'mail_disc'
        ['Mail', k]
      when 'other_disc'
        ['Other', k]
      else
        [k.humanize,k]
      end
    end
  end

  def method_received_options
    Order.method_receiveds.map { |k,v| [k.humanize,k] }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def items_for_select(form)
    options_for_select(Item.all.map { |i| [i.title, i.id, {:'data-img-src' => image_path(i.image_path)}] }, form.item_ids)
  end

  def active_items_for_select(form)
    options_for_select(Item.active.map { |i| [i.title, i.id, {:'data-img-src' => image_path(i.image_path)}] }, form.item_ids)
  end

  def titles_for_select(form)
    options_for_select(['Mr', 'Mrs', 'Miss','Ms'], form.title)
  end

  def discovery_methods_for_select(form)
    options_for_select(method_of_discovery_options, form.method_of_discovery)
  end

  def methods_received_for_select(form)
    options_for_select(method_received_options, form.method_received)
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, order_form], url: admin_customer_orders_path(order_form.customer), remote: true, html: {role: "form", class: "form-horizontal"} do |f| %>
  <div class="col-md-4">
    <dl>
      <dt><%= f.label :method_received, class: "control-label"%></dt>
      <dd><%= f.select :method_received, methods_received_for_select(order_form), {include_blank: true}, class: "form-control" %></dd>
    </dl>
    <dl>
      <dt><%= f.label :method_of_discovery, class: "control-label"%></dt>
      <dd><%= f.select :method_of_discovery, discovery_methods_for_select(order_form), {include_blank: true}, class: "form-control" %></dd>
    </dl>
  </div>

  <div class="col-md-8">
    <dl>
      <dt><%= f.label :item_ids, "Titles requested", class: "control-label" %></dt>
      <div class="error_msg"><%= order_form.errors[:item_ids].join %></div>
      <dd><%= f.select :item_ids, items_for_select(order_form), {}, multiple: 'multiple', size: 6, class: "form-control imagepicker" %></dd>
    </dl>

    <div class="checkbox">
      <%= f.label :received_in_person do %>
        <%= f.check_box :received_in_person %>This order has already been delivered.
      <% end %>
    </div>
  </div>

  <div class="btn-toolbar">
    <div class="col-sm-8">
      <%= f.submit "Create Order", class: "btn btn-primary" %>
      <%= link_to "Discard", '#', class: 'btn btn-default', id: "discard-order" %>
    </div>
  </div>
<% end %>

app/views/admin/orders/create.js.erb
<% if @create_order.success? %>
  <% flash_type = :success %>
  $("#orders").html("<%= escape_javascript(render 'admin/customers/orders', view_model: @edit_customer_view) %>")
<% else %>
  <% flash_type = :error %>
  $("#order-form").html("<%= escape_javascript(render 'form', order_form: @order_form) %>")
<% end %>

<%= render 'shared/flash_messages', header_class: 'orders', text: @create_order.message, type: flash_type %>

app/views/admin/orders/destroy.js.erb
<% if @cancel_order.success? %>
  <% flash_type = :success %>
<% else %>
  <% flash_type = :error %>
<% end %>

$("#orders").html("<%= escape_javascript(render 'admin/customers/orders', view_model: @edit_customer_view) %>")

<%= render 'shared/flash_messages', header_class: 'orders', text: @cancel_order.message, type: flash_type %>

app/views/admin/orders/new.js.erb
$("#order-form").html("<%= escape_javascript(render 'form', order_form: @order_form) %>")

app/views/admin/orders/update.js.erb
<% if @update_order.success? %>
  <% flash_type = :success %>
<% else %>
  <% flash_type = :error %>
  $("#<%= @order_view_model.form_id %>").html("<%= escape_javascript(render 'admin/customers/editable_order', presenter: @order_view_model) %>")
<% end %>

<%= render 'shared/flash_messages', header_class: 'orders', text: @update_order.message, type: flash_type %>