config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/AboutTheBible',:as => 'aboutthebible_page'

  get 'staticpages/FAQ',:as => 'FAQ_page'

  get 'staticpages/Links',:as => 'Links_page'

  get 'staticpages/BibleTranslation',:as => 'bibletranslation_page'

  get 'staticpages/QuickRef',:as => 'quickref_page'

  get 'staticpages/Sample',:as => 'sample_page'

  get 'staticpages/Subject',:as => 'subject_page'

  get 'staticpages/Gospel',:as => 'gospel_page'

  get 'staticpages/Books',:as => 'books_page'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

   root 'home#index'

  resources :tables, except: [:show, :index]
  get 'table/new' => redirect('tables/new')
  get 'table' => 'tables#show', as: :show_table
  get 'tables' => redirect('table')
  post 'table/exit' => 'tables#exit_table', as: :exit_table

  resources :orders, only: [:new, :create]
  post 'orders/create_table_order' => 'orders#create_table_order', as: :create_table_order

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create]

  namespace :admin do
    get '/' => 'home#index', as: :root
    get '/orders' => 'search#index'
    get '/duplicates_csv' => 'search#duplicates_csv'

    resources :users, only: [:index, :edit, :update]

    resources :customers, only: [:new, :create, :edit, :update] do
      post 'find_duplicate_by_name_or_address', on: :collection
      member do
        get 'find_duplicate'
        post 'merge'
      end
      resources :orders, only: [:new, :create, :destroy, :update]
    end

    resources :labels, only: [:index]
    resources :shipments, only: [:index, :show]
    resources :contact_lists, only: [:index, :show, :create]
    resources :coordinators, except: [:show, :destroy]
    resources :users
    resources :inventories do
      collection do
        post :stock_take
        post :stock_in
        post :reset_table
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'available_items' => 'home#available_items'
      post 'validate_order' => 'orders#validate'
      post 'orders' => 'orders#create'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |config|
    config.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  validates :password, confirmation: { if: :require_password? }, length: { minimum: 4, if: :require_password? }

  has_many :territorial_authorities, foreign_key: :coordinator_id

  scope :coordinators, -> { where(admin: false) }
  scope :unassigned_coordinators, -> {
    coordinators.
    joins('LEFT OUTER JOIN territorial_authorities ON territorial_authorities.coordinator_id = users.id').
    where('territorial_authorities.coordinator_id IS NULL')
  }

  validates :name, :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  def new_contacts
    Customer.contactable.for_districts(territorial_authorities.pluck(:id))
  end

  def superadmin?
    superadmin
  end
end

app/controllers/admin/coordinators_controller.rb
class Admin::CoordinatorsController < Admin::BaseController

  def index
    @territorial_authorities = TerritorialAuthority.order(:name)
    @unassigned_coordinators = User.unassigned_coordinators
  end

  def new
    @coordinator = User.new
  end

  def create
    coordinator_service = Admin::CreateCoordinatorService.new(params)
    if coordinator_service.save
      redirect_to admin_coordinators_path, notice: "Coordinator created successfully."
    else
      flash[:alert] = coordinator_service.error_message
      @coordinator = coordinator_service.coordinator
      render :new
    end
  end

  def edit
    @coordinator = User.coordinators.find(params[:id])
  end

  def update
    coordinator_service = Admin::UpdateCoordinatorService.new(params)
    if coordinator_service.save
      redirect_to admin_coordinators_path, notice: "Coordinator updated successfully."
    else
      @coordinator = coordinator_service.coordinator
      render :edit
    end
  end
end

app/views/admin/coordinators/_coordinator.html.erb
<% if coordinator %>
  <td><%= coordinator.name %></td>
  <td><%= coordinator.email %></td>
  <td>
    <div class='btn-group-vertical'>
      <%= link_to 'Edit', edit_admin_coordinator_path(coordinator), class: 'btn btn-default' %>
    </div>
  </td>
<% else %>
  <td colspan="3"></td>
<% end %>

app/views/admin/coordinators/_form.html.erb
<div class="form-group">
  <div class="col-xs-6">
    <%= form.required_label :name, class: "control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-xs-6">
    <%= form.required_label :email, class: "control-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-xs-12">
    <%= form.label :territorial_authority_ids, "Districts", class: "control-label" %>
  </div>
  <%= hidden_field_tag 'coordinator[territorial_authority_ids][]' %>
  <% TerritorialAuthority.order(:name).in_groups_of(22) do |group| %>
    <div class="col-xs-4">
      <% group.each do |ta| %>
        <% if ta %>
          <div class="checkbox district">
            <label for="coordinator_territorial_authority_ids_<%= ta.id %>">
              <%= form.check_box :territorial_authority_ids, {multiple: true}, ta.id, nil %><%= ta.name %>
            </label>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="form-group">
  <div class="col-sm-4">
    <%= form.submit "Save", class: "btn btn-success" %>
    <%= link_to "Cancel", admin_coordinators_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/coordinators/edit.html.erb
<h2>Edit Coordinator</h2>
<%= form_for [:admin, @coordinator], as: :coordinator, url: admin_coordinator_path(@coordinator), html: {role: "form", class: "form-horizontal"} do |form| %>
  <%= render form %>
<% end %>

app/views/admin/coordinators/index.html.erb
<h2>Coordinators</h2>

<p><%= link_to "Add Coordinator", new_admin_coordinator_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>District</th>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @territorial_authorities.each do |ta| %>
      <tr class="<%= ta.addressfinder_name %>">
        <td><%= ta.name %></td>
        <%= render 'coordinator', coordinator: ta.coordinator %>
      </tr>
    <% end %>
    <% @unassigned_coordinators.each do |coordinator| %>
      <tr>
        <td><i>Unassigned</i></td>
        <%= render 'coordinator', coordinator: coordinator %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/coordinators/new.html.erb
<h2>Add Coordinator</h2>
<%= form_for [:admin, @coordinator], as: :coordinator, url: admin_coordinators_path, html: {role: "form", class: "form-horizontal"} do |form| %>
  <%= render form %>
<% end %>