config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/AboutTheBible',:as => 'aboutthebible_page'

  get 'staticpages/FAQ',:as => 'FAQ_page'

  get 'staticpages/Links',:as => 'Links_page'

  get 'staticpages/BibleTranslation',:as => 'bibletranslation_page'

  get 'staticpages/QuickRef',:as => 'quickref_page'

  get 'staticpages/Sample',:as => 'sample_page'

  get 'staticpages/Subject',:as => 'subject_page'

  get 'staticpages/Gospel',:as => 'gospel_page'

  get 'staticpages/Books',:as => 'books_page'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

   root 'home#index'

  resources :tables, except: [:show, :index]
  get 'table/new' => redirect('tables/new')
  get 'table' => 'tables#show', as: :show_table
  get 'tables' => redirect('table')
  post 'table/exit' => 'tables#exit_table', as: :exit_table

  resources :orders, only: [:new, :create]
  post 'orders/create_table_order' => 'orders#create_table_order', as: :create_table_order

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create]

  namespace :admin do
    get '/' => 'home#index', as: :root
    get '/orders' => 'search#index'
    get '/duplicates_csv' => 'search#duplicates_csv'

    resources :users, only: [:index, :edit, :update]

    resources :customers, only: [:new, :create, :edit, :update] do
      post 'find_duplicate_by_name_or_address', on: :collection
      member do
        get 'find_duplicate'
        post 'merge'
      end
      resources :orders, only: [:new, :create, :destroy, :update]
    end

    resources :labels, only: [:index]
    resources :shipments, only: [:index, :show]
    resources :contact_lists, only: [:index, :show, :create]
    resources :coordinators, except: [:show, :destroy]
    resources :users
    resources :inventories do
      collection do
        post :stock_take
        post :stock_in
        post :reset_table
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'available_items' => 'home#available_items'
      post 'validate_order' => 'orders#validate'
      post 'orders' => 'orders#create'
    end
  end
end

app/controllers/admin/search_controller.rb
require 'csv'

module Admin
  class SearchController < BaseController
    before_action :permit_params

    def index
      @order_search = OrderSearchForm.new(params[:admin_order_search_form])
      orders = @order_search.filtered_orders
      params[:format] = 'csv' if params[:csv]
      respond_to do |format|
        format.html do
          @orders_presenter = OrdersPresenter.new(orders, params[:page])
        end
        format.csv do
          @order_view_models = orders.map { |order| Admin::Orders::CsvView.new(order) }
          headers['Content-Disposition'] = "attachment; filename=\"orders.csv\""
          headers['Content-Type'] = 'text/csv'
        end
      end
    end

    def duplicates_csv
      filename = "new_dup_#{Time.now.strftime('%Y-%m-%d_%H-%M-%S')}.csv"
      send_data Admin::DuplicateFinder.new.csv, filename: filename
    end
  end
end

app/views/admin/search/_search.html.erb
<%= form_for order_search, url: admin_orders_path, html: {class: "form-horizontal", role: "form", method: :get} do |f| %>

  <!--TODO Can we have an indicator or message next to the list that shows when an address does not have a pxid -->
  <div class="form-group">
    <label class="col-xs-1">Name</label>
    <div class="col-xs-2">
      <%= f.label :first_name, class: "sr-only" %>
      <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>
    </div>
    <div class="col-xs-2">
      <%= f.label :last_name, class: "sr-only" %>
      <%= f.text_field :last_name, class: "form-control", placeholder: "Last name" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Customer ID</label>
    <div class="col-xs-2">
      <%= f.label :customer_id, class: "sr-only" %>
      <%= f.text_field :customer_id, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Contact info</label>
    <div class="col-xs-2">
      <%= f.label :email, class: "sr-only" %>
      <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
    </div>
    <div class="col-xs-2">
      <%= f.label :phone, "Phone", class: "sr-only" %>
      <%= f.text_field :phone, class: "form-control", placeholder: "Phone number" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Address</label>
    <div class="col-xs-2">
      <%= f.label :address, class: "sr-only" %>
      <%= f.text_field :address, class: "form-control", placeholder: "Street address" %>
    </div>
    <div class="col-xs-2">
      <%= f.label :suburb, class: "sr-only" %>
      <%= f.text_field :suburb, class: "form-control", placeholder: "Suburb" %>
    </div>
    <div class="col-xs-2">
      <%= f.label :city_town, "City/Town", class: "sr-only" %>
      <%= f.text_field :city_town, class: "form-control", placeholder: "City/Town" %>
    </div>
    <div class="col-xs-4">
      <%= f.label :district, "TA / Distrct", class: "sr-only" %>
      <%= f.select :district, order_search.district_options, {include_blank: "All Districts"}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Creator Email</label>
    <div class="col-xs-4">
      <%= f.label :creator_email, class: "sr-only" %>
      <%= f.text_field :creator_email, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Created Date</label>
    <div class="col-xs-1">
      <%= f.label :created_at_from, class: "sr-only" %>
      <%= f.text_field :created_at_from, class: "form-control datepicker", placeholder: "From" %>
    </div>
    <div class="col-xs-1">
      <%= f.label :created_at_to, class: "sr-only" %>
      <%= f.text_field :created_at_to, class: "form-control datepicker", placeholder: "To" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Shipped Date</label>
    <div class="col-xs-1">
      <%= f.label :shipped_at_from, class: "sr-only" %>
      <%= f.text_field :shipped_at_from, class: "form-control datepicker", placeholder: "From" %>
    </div>
    <div class="col-xs-1">
      <%= f.label :shipped_at_to, class: "sr-only" %>
      <%= f.text_field :shipped_at_to, class: "form-control datepicker", placeholder: "To" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-1">Order info</label>
    <div class="col-xs-1">
      <%= f.label :id, "ID" %>
      <%= f.text_field :id, class: "form-control" %>
    </div>

    <div class="col-xs-1">
      <%= f.label :shipped, "Shipped?" %>
      <%= f.select :shipped, order_search.yes_no_options, {include_blank: true}, {class: "form-control"} %>
    </div>

    <div class="col-xs-2">
      <%= f.label :further_contact_requested, "Further Contact?" %>
      <%= f.select :further_contact_requested, order_search.further_contact_options, {include_blank: true}, {class: "form-control"} %>
    </div>

    <div class="col-xs-3">
      <%= f.label :item_ids, "Items" %>
      <%= f.select :item_ids, order_search.item_ids_options, {}, {class: "form-control", multiple: :multiple} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit "Search", class: "btn btn-default" %>
    <%= f.button "Export to CSV", name: 'format', value: 'csv', class: "btn btn-default" %>
    <%= link_to "Reset", admin_orders_path, class: "btn btn-default" %>
    <%= link_to "Download Duplicates", admin_duplicates_csv_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/search/index.csv.erb
<%- headers = ["ID",
               "Title",
               "First name",
               "Last name",
               "Street address",
               "Phone",
               "Email",
               "Method received",
               "Item codes",
               "Contact wanted",
               "Admin notes",
               "Suburb",
               "City/Town",
               "Postcode",
               "Region",
               "Shipped at",
               "Shipment ID",
               "IP address",
               "Tertiary student",
               "Tertiary institution",
               "User name",
               "User email",
               "Method of discovery",
               "Created at",
              ]-%>

<%= CSV.generate_line headers %>
<%- @order_view_models.each do |view_model| -%>
  <%=raw CSV.generate_line([view_model.id,
                            view_model.title,
                            view_model.first_name,
                            view_model.last_name,
                            view_model.address,
                            view_model.phone,
                            view_model.email,
                            view_model.method_received,
                            view_model.item_codes,
                            view_model.further_contact_requested,
                            view_model.admin_notes,
                            view_model.suburb,
                            view_model.city_town,
                            view_model.post_code,
                            view_model.ta,
                            view_model.shipped_at,
                            view_model.shipment_id,
                            view_model.ip_address,
                            view_model.tertiary_student,
                            view_model.tertiary_institution,
                            view_model.creator_name,
                            view_model.creator_email,
                            view_model.method_of_discovery,
                            view_model.created_at,
                           ]) -%>
<%- end -%>

app/views/admin/search/index.html.erb
<h2>Search Orders</h2>

<%= render 'search', :order_search => @order_search %>

<div><%= page_entries_info @orders_presenter.orders_for_current_page %></div>
<%= paginate @orders_presenter.orders_for_current_page %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Created</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Items</th>
      <th>Further Contact Requested?</th>
      <th>Shipped At</th>
    </tr>
  </thead>
  <tbody>
    <% @orders_presenter.order_presenters do |presenter| %>
      <tr class="<%= 'danger' unless presenter.pxid %>">
        <td>
          <% unless presenter.pxid %>
            <i class="fa fa-exclamation-triangle text-danger" aria-hidden="true"></i>
          <% end %>
          <%= presenter.order_number %>
        </td>
        <td><%= presenter.created %></td>
        <td><%= presenter.first_name %></td>
        <td><%= presenter.last_name %></td>
        <td><%= presenter.items %></td>
        <td><%= presenter.further_contact_requested %></td>
        <td><%= presenter.shipped_at %></td>
        <td>
          <div class='btn-group-vertical'>
            <%= link_to 'Edit', edit_admin_customer_path(presenter.customer_id), class: 'btn btn-default' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders_presenter.orders_for_current_page %>